# REST

## 1.Admin
### 1.1 Register
POST http://localhost:9092/api/auth/local/register
Content-Type: application/json

{
    "username": "kantapon_final",
    "email": "kantapon.final@gmail.com",
    "password": "FinalPassword123!"
}

### 1.2 Login
POST http://localhost:9092/api/auth/local
Content-Type: application/json

{
    "identifier": "kantapon.final@gmail.com",
    "password": "FinalPassword123!",
    "rememberMe": false
}

### 1.3 Forgot Password
POST http://localhost:9092/api/auth/forgot-password
Content-Type: application/json

{
    "email": "kantapon.final@gmail.com"
}

### 1.4 Reset Password
POST http://localhost:9092/api/auth/reset-password
Content-Type: application/json

{
    "code": "d32e2d6fe3076f2baccbd84b6d023d1f0214e30b5e369725f603ce0787ebd44386eab769f38c81cbb29a5a7b96dd7ec84494bb919cd7d28447fe725da6ca261e",  
    "password": "NewPassword123!",
    "passwordConfirmation": "NewPassword123!"
}

### 1.5 Profile
GET http://localhost:9092/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNzg3OTI5MzI0LCJleHAiOjE3OTA1MjEzMjR9._pwWKk0M8vC4Virj7c74JPtekKjFtM80v4AAOob1srU
Content-Type: application/json

## 2. User
### 2.1 Register
POST http://localhost:9092/api/auth/local/register
Content-Type: application/json

{
    "username": "kantapon_user_final",
    "email": "kantapon.user.final@gmail.com",
    "password": "FinalUserPassword123!"
}

### 2.2 Login
POST http://localhost:9092/api/auth/local
Content-Type: application/json
    
{
    "identifier": "kantapon_user_final",
    "password": "FinalUserPassword123!"
}

### 2.3 Forgot Password
POST http://localhost:9092/api/auth/forgot-password
Content-Type: application/json

{
    "email": "kantapon.user3@gmail.com"
}

### 2.4 Profile
GET http://localhost:9092/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNzg3OTI5NDYwLCJleHAiOjE3OTA1MjE0NjB9.NkJYzLW1bRUiS-bJ0-L-xPbcJTiwffdO26GyMOwPf-o
Content-Type: application/json