services:

  69-s2-db:
    image: postgres:16
    container_name: 69-s2-db
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - 69-s2-cybersec

  69-s2-admin:
    image: prawee/strapi
    container_name: 69-s2-admin
    env_file:
      - .env
    ports:
      - "9091:1337"
    depends_on:
      - 69-s2-db
    networks:
      - 69-s2-cybersec

  69-s2-app:
    image: prawee/strapi
    container_name: 69-s2-app
    env_file:
      - .env
    ports:
      - "9092:1337"
    depends_on:
      - 69-s2-db
    networks:
      - 69-s2-cybersec

networks:
  69-s2-cybersec:
    driver: bridge

volumes:
  postgres_data:
