services:
  db:
    image: postgres:16-alpine
    container_name: 69-s2-db
    ports:
      - 54321:5432
    environment:
      - POSTGRES_PASSWORD=$kanta057
      - POSTGRES_USER=$kanta057
      - POSTGRES_DB=$uno507
volumes:
      - ./data-postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: 69-s2-pgadmin
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=$Kantapon-v@rmutp.ac.th
      - PGADMIN_DEFAULT_PASSWORD=$Kanta5057-1

admin:
    image: dpage/pgadmin4:latest
    container_name: 69-s2-admin
     ports:
      - 8082:80
      environment:
      - PGADMIN_DEFAULT_EMAIL=$Kantapon-v@rmutp.ac.th
      - PGADMIN_DEFAULT_PASSWORD=$Kanta5057-1

  volumes:
  data-postgres
